excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://myaggregatethoughts.github.io
title: myaggregatethoughts
tagline: A log of everyday life
description: My awesome new site
paginate: 5